-define(GAME_OPCODE_LEN, 16).

-define(GAME_OP_NOOP, 0).
-define(GAME_HDR_NOOP, ?GAME_OP_NOOP:?GAME_OPCODE_LEN).

-define(GAME_OP_IDENT, 10).
-define(GAME_HDR_IDENT, ?GAME_OP_IDENT:?GAME_OPCODE_LEN).

-define(GAME_OP_READY, 11).
-define(GAME_HDR_READY, ?GAME_OP_READY:?GAME_OPCODE_LEN).

-define(GAME_OP_PING, 21).
-define(GAME_HDR_PING, ?GAME_OP_PING:?GAME_OPCODE_LEN).

-define(GAME_OP_PONG, 22).
-define(GAME_HDR_PONG, ?GAME_OP_PONG:?GAME_OPCODE_LEN).

-define(GAME_OP_HELLO, 50).
-define(GAME_HDR_HELLO, ?GAME_OP_HELLO:?GAME_OPCODE_LEN).

-define(GAME_OP_ENTER_WORLD, 100).
-define(GAME_HDR_ENTER_WORLD, ?GAME_OP_ENTER_WORLD:?GAME_OPCODE_LEN).

-define(GAME_OP_SPAWN_WORLD_ENTITY, 101).
-define(GAME_HDR_SPAWN_WORLD_ENTITY, ?GAME_OP_SPAWN_WORLD_ENTITY:?GAME_OPCODE_LEN).

-define(GAME_OP_DESTROY_WORLD_ENTITY, 102).
-define(GAME_HDR_DESTROY_WORLD_ENTITY, ?GAME_OP_DESTROY_WORLD_ENTITY:?GAME_OPCODE_LEN).

-define(GAME_OP_MOVE_WORLD_ENTITY, 103).
-define(GAME_HDR_MOVE_WORLD_ENTITY, ?GAME_OP_MOVE_WORLD_ENTITY:?GAME_OPCODE_LEN).

-define(GAME_OP_WORLD_ENTITY_DISCO, 104).
-define(GAME_HDR_WORLD_ENTITY_DISCO, ?GAME_OP_WORLD_ENTITY_DISCO:?GAME_OPCODE_LEN).