-define(WORLD_OPCODE_LEN, 16).

-define(WORLD_OP_NOOP, 0).
-define(WORLD_HDR_NOOP, ?WORLD_OP_NOOP:?WORLD_OPCODE_LEN).

-define(WORLD_OP_HELLO, 10).
-define(WORLD_HDR_HELLO, ?WORLD_OP_HELLO:?WORLD_OPCODE_LEN).

-define(WORLD_OP_ENTER_WORLD, 100).
-define(WORLD_HDR_ENTER_WORLD, ?WORLD_OP_ENTER_WORLD:?WORLD_OPCODE_LEN).

-define(WORLD_OP_SPAWN_WORLD_ENTITY, 101).
-define(WORLD_HDR_SPAWN_WORLD_ENTITY, ?WORLD_OP_SPAWN_WORLD_ENTITY:?WORLD_OPCODE_LEN).

-define(WORLD_OP_WORLD_ENTITY_DISCO, 104).
-define(WORLD_HDR_WORLD_ENTITY_DISCO, ?WORLD_OP_WORLD_ENTITY_DISCO:?WORLD_OPCODE_LEN).